"""added create at

Revision ID: 87644d65d382
Revises: ab2274e494ff
Create Date: 2024-06-09 17:34:31.252504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87644d65d382'
down_revision = 'ab2274e494ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
