"""fixed foreign keydata type

Revision ID: 9fdb32130466
Revises: 
Create Date: 2024-06-09 16:37:34.389887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fdb32130466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('workout_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('duration_min', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'workout_type', ['workout_type_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duration_min')
        batch_op.drop_column('workout_type_id')
        batch_op.drop_column('workout_date')

    # ### end Alembic commands ###
